<?php
namespace app\home\controller;

use think\Db;
use think\Session;

class Upfile extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->login();
    }
    public function upload(){
        $fileKey = array_keys(request()->file());
        // 获取表单上传文件
        $file = request()->file($fileKey['0']);
        $info = $file->validate(['ext' => 'jpg,png,gif,jpeg'])->move('upload/qrcode');
        if($info){
            $path=str_replace('\\','/',$info->getSaveName());
            $path = '/upload/qrcode/'. $path;
            $QRCodeReader = new \Libern\QRCodeReader\QRCodeReader();
            $text = $QRCodeReader->decode(ROOT_PATH . 'public' .$path);
            echo json_encode(array("code" => 1, "msg" => "成功", "data" => $text,'qrcode'=>$path));
        }
    }
}
